#include "CharacterController.h"

#include "Game/Audio.h"
#include "Game/World.h"
#include "Game/Game.h"
#include "Game/Item.h"
#include "Game/Physics/Physics.h"
#include "Game/Physics/PhysicsUtils.h"

#include "Jolt/Physics/Character/CharacterBase.h"
#include "Jolt/Physics/Constraints/DistanceConstraint.h"
#include "tracy/Tracy.hpp"

void Systems::UpdateCharacterControllers(World& world, float dt)
{
  // Apply input (could be generated by players or NPCs!)
  // if (IsServer())
  {
    ZoneScoped;
    auto& registry_ = world.GetRegistry();

    for (auto&& [entity, input, transform] : registry_.view<const InputState, LocalTransform>(entt::exclude<GhostPlayer>).each())
    {
      if (!world.IsServer() && !registry_.all_of<LocalAuthoritative>(entity))
      {
        continue;
      }
      // Movement
      if (registry_.all_of<const NoclipCharacterController>(entity))
      {
        const auto right     = GetRight(transform.rotation);
        const auto forward   = GetForward(transform.rotation);
        auto tempCameraSpeed = 14.5f;
        tempCameraSpeed *= input.sprint ? 4.0f : 1.0f;
        tempCameraSpeed *= input.walk ? 0.25f : 1.0f;
        auto velocity = glm::vec3(0);
        velocity += input.forward * forward * tempCameraSpeed;
        velocity += input.strafe * right * tempCameraSpeed;
        velocity.y += input.elevate * tempCameraSpeed;
        transform.position += velocity * dt;
        world.UpdateLocalTransform(entity);
        registry_.get_or_emplace<LinearVelocity>(entity).v = velocity;
      }

      if (auto* fc = registry_.try_get<const FlyingCharacterController>(entity))
      {
        auto& velocity     = registry_.get<LinearVelocity>(entity).v;
        const auto right   = GetRight(transform.rotation);
        const auto forward = GetForward(transform.rotation);
        const auto dv      = fc->acceleration * dt;

        velocity += input.forward * forward * dv;
        velocity += input.strafe * right * dv;
        velocity += input.elevate * glm::vec3(0, 1, 0) * dv;

        if (glm::length(velocity) > fc->maxSpeed)
        {
          velocity = glm::normalize(velocity) * fc->maxSpeed;
        }

        transform.position += velocity * dt;

        world.UpdateLocalTransform(entity);
      }

      if (auto* attribs = registry_.try_get<WalkingMovementAttributes>(entity);
        attribs && registry_.any_of<Physics::CharacterController, Physics::CharacterControllerShrimple>(entity))
      {
        const auto rot   = glm::mat3_cast(transform.rotation);
        const auto right = rot[0];
        const auto gUp   = glm::vec3(0, 1, 0);
        // right and up will never be collinear if roll doesn't change
        const auto forward = glm::normalize(glm::cross(gUp, right));

        // Physics engine factors in deltaTime already
        float tempSpeed = attribs->acceleration * dt;
        tempSpeed *= input.walk ? attribs->walkModifier : 1.0f;

        const bool isInWater = world.DescendantHasComponent<IsInWater>(entity).has_value();

        auto deltaVelocity = glm::vec3(0);
        deltaVelocity.y =
          (isInWater ? Item::GetTotalEffectOnEntity(world, entity, Item::EffectType::WaterGravityModifier, attribs->waterGravity) : attribs->gravity) * dt;
        attribs->timeSinceJumped += dt;

        if (auto* cc = registry_.try_get<const Physics::CharacterController>(entity))
        {
          auto* player            = registry_.try_get<Player>(entity);
          auto& velocity          = registry_.get<LinearVelocity>(entity).v;
          const auto realVelocity = (transform.position - cc->previousPosition) / dt;
          if (player && player->attachedToRope)
          {
            velocity = realVelocity;
          }
          else
          {
            velocity = glm::length(realVelocity) < glm::length(velocity) ? realVelocity : velocity;
          }

          if (player && player->attachedToRope && input.walk)
          {
            const auto fakePhysics = world.GetChildNamed(entity, "Player fake physics");
            player->attachedToRope = false;
            world.GetPhysicsEngine().RemoveConstraintsFromBody(registry_.get<const Physics::RigidBody>(fakePhysics).body);
          }

          const bool isOnGround    = cc->character->GetGroundState() == JPH::CharacterBase::EGroundState::OnGround;
          const float acceleration = isInWater
                                       ? Item::GetTotalEffectOnEntity(world, entity, Item::EffectType::WaterAccelerationModifier, attribs->waterAcceleration)
                                       : (isOnGround ? attribs->acceleration : attribs->airAcceleration);
          deltaVelocity += input.forward * forward * acceleration * (input.walk ? attribs->walkModifier : 1.0f) * dt;
          deltaVelocity += input.strafe * right * acceleration * (input.walk ? attribs->walkModifier : 1.0f) * dt;

          auto* emitter = registry_.try_get<SoundEmitter>(entity);
          if (isOnGround && glm::length(glm::vec2(velocity.x, velocity.z)) >= attribs->runMaxSpeed * 0.5f)
          {
            if (!emitter || emitter->handle.expired())
            {
              registry_.emplace_or_replace<SoundEmitter>(entity,
                SoundEmitter{world.GetAudio()->PlaySound({
                  .name        = "walk",
                  .volume      = 1,
                  .minDistance = 3,
                  .isLooping   = true,
                  .delay       = 0.1f,
                  .position    = registry_.all_of<LocalPlayer>(entity) ? std::nullopt : std::optional(transform.position),
                })});
            }
          }
          else if (emitter && !emitter->handle.expired())
          {
            emitter->handle.lock()->SetIsLooping(false);
          }

          if (isOnGround && cc->previousGroundState != JPH::CharacterBase::EGroundState::OnGround && velocity.y < -1.0f)
          {
            world.GetAudio()->PlaySound({
              .name        = "walk",
              .minDistance = 3,
              .pitch       = 0.8f,
              .position    = registry_.all_of<LocalPlayer>(entity) ? std::nullopt : std::optional(transform.position),
            });
          }

          if (isOnGround || (player && player->attachedToRope))
          {
            if (input.jump)
            {
              const auto doJump = [&]
              {
                world.GetAudio()->PlaySound({
                  .name        = "jump",
                  .volume      = 0.4f,
                  .minDistance = 3,
                  .pitch       = 0.8f,
                  .position    = registry_.all_of<LocalPlayer>(entity) ? std::nullopt : std::optional(transform.position),
                });

                velocity.y = Item::GetTotalEffectOnEntity(world,
                  entity,
                  Item::EffectType::JumpImpulseModifier,
                  isInWater ? attribs->waterJumpImpulse : attribs->jumpInitialImpulse);

                deltaVelocity.y = 0;
              };

              if (player && player->attachedToRope)
              {
                player->attachedToRope = false;
                const auto fakePhysics = world.GetChildNamed(entity, "Player fake physics");
                const auto constraints = world.GetPhysicsEngine().GetConstraintsForBody(registry_.get<const Physics::RigidBody>(fakePhysics).body);
                bool shouldJump        = isOnGround;
                for (auto* constraint : constraints)
                {
                  if (constraint->GetSubType() == JPH::EConstraintSubType::Distance)
                  {
                    [[maybe_unused]] const auto* dConstraint = static_cast<const JPH::DistanceConstraint*>(constraint);
                    const auto pos1 = Physics::ToGlm(world.GetPhysicsEngine().GetBodyInterface().GetPosition(constraint->GetBody1()->GetID()));
                    const auto pos2 = Physics::ToGlm(world.GetPhysicsEngine().GetBodyInterface().GetPosition(constraint->GetBody2()->GetID()));
                    // if (abs(dConstraint->GetMinDistance() - dConstraint->GetMaxDistance()) < 0.5f)
                    if (glm::distance(pos1, pos2) < 1.0f)
                    {
                      shouldJump = true;
                    }
                    world.GetPhysicsEngine().DestroyConstraint(constraint);
                  }
                }

                if (shouldJump)
                {
                  doJump();
                }
              }
              else
              {
                doJump();
              }
            }
            attribs->timeSinceJumped = 0;
          }

          if (input.jump && attribs->timeSinceJumped <
                              (isInWater ? Item::GetTotalEffectOnEntity(world, entity, Item::EffectType::WaterJumpControlTimeModifier, attribs->waterJumpControlTime)
                                         : attribs->jumpControlTime))
          {
            velocity.y += attribs->jumpAcceleration * dt;
          }

          // Reduce acceleration from normal input if it would make the character go over its max speed.
          auto deltaXZ1      = glm::vec2(deltaVelocity.x, deltaVelocity.z);
          auto xzVel         = glm::vec2(velocity.x, velocity.z);
          const auto xzSpeed = glm::length(xzVel);
          const auto baseMaxSpeed =
            (isInWater ? Item::GetTotalEffectOnEntity(world, entity, Item::EffectType::WaterMaxSpeedModifier, attribs->waterMaxSpeed) : attribs->runMaxSpeed) *
            (input.walk ? attribs->walkModifier : 1.0f);
          const auto realMaxSpeed = Item::GetTotalEffectOnEntity(world, entity, Item::EffectType::MovementSpeedModifier, baseMaxSpeed);
          if (glm::length(deltaXZ1 + xzVel) > realMaxSpeed)
          {
            const auto nextXZVel = glm::normalize(deltaXZ1 + xzVel) * glm::max(realMaxSpeed, xzSpeed);
            deltaXZ1             = nextXZVel - xzVel;
            deltaVelocity.x      = deltaXZ1[0];
            deltaVelocity.z      = deltaXZ1[1];
          }

          const float deceleration = [&]
          {
            if (isInWater)
            {
              return attribs->waterDeceleration;
            }

            // Rope movement feels better when there's no air deceleration.
            if (player && player->attachedToRope)
            {
              return 0.0f;
            }

            if (isOnGround && !input.jump)
            {
              return attribs->deceleration;
            }

            return attribs->airDeceleration;
          }();

          // Decelerate when no forward input is present.
          const auto velocityXZ = glm::vec2(velocity.x, velocity.z);
          const auto forwardXZ  = glm::normalize(glm::vec2(forward.x, forward.z));
          auto forwardVel       = forwardXZ * glm::dot(velocityXZ, forwardXZ);
          if (input.forward == 0 && glm::length(forwardVel) > 1e-3f)
          {
            auto deltaXZ = glm::vec2(deltaVelocity.x, deltaVelocity.z);
            auto offs    = -glm::normalize(forwardVel) * deceleration * dt;
            if (glm::dot(offs + forwardVel, forwardVel) < 0)
            {
              offs = -forwardVel;
            }
            deltaXZ += offs;
            deltaVelocity.x = deltaXZ[0];
            deltaVelocity.z = deltaXZ[1];
          }

          // Decelerate when no strafe input is present.
          const auto rightXZ = glm::normalize(glm::vec2(right.x, right.z));
          auto rightVel      = rightXZ * glm::dot(velocityXZ, rightXZ);
          if (input.strafe == 0 && glm::length(rightVel) > 1e-3f)
          {
            auto deltaXZ = glm::vec2(deltaVelocity.x, deltaVelocity.z);
            auto offs    = -glm::normalize(rightVel) * deceleration * dt;
            if (glm::dot(offs + rightVel, rightVel) < 0)
            {
              offs = -rightVel;
            }
            deltaXZ += offs;
            deltaVelocity.x = deltaXZ[0];
            deltaVelocity.z = deltaXZ[1];
          }

          velocity += deltaVelocity;

          // Apply penalty force if going over max speed.
          auto xzVel2         = glm::vec2(velocity.x, velocity.z);
          const auto xzSpeed2 = glm::length(xzVel2);
          if (xzSpeed2 > realMaxSpeed)
          {
            xzVel2 += -glm::normalize(xzVel2) * deceleration * dt;
            // Set speed to max if this penalty would put us under it.
            if (glm::length(xzVel2) < realMaxSpeed)
            {
              xzVel2 = glm::normalize(xzVel2) * realMaxSpeed;
            }
            // Reverse direction if penalty would make us go backwards (this can happen when the max speed is very low relative to dt).
            if (glm::dot(glm::vec2(velocity.x, velocity.z), xzVel2) < 0)
            {
              xzVel2 *= -1;
            }
            velocity.x = xzVel2[0];
            velocity.z = xzVel2[1];
          }

          velocity.y = glm::max(velocity.y, isInWater ? attribs->waterTerminalVelocity : attribs->terminalVelocity);
        }
        else
        {
          deltaVelocity += input.forward * forward * tempSpeed;
          deltaVelocity += input.strafe * right * tempSpeed;
        }

        if (auto* cs = registry_.try_get<const Physics::CharacterControllerShrimple>(entity))
        {
          auto velocity                 = registry_.get<LinearVelocity>(entity).v;
          auto& friction                = registry_.get_or_emplace<Friction>(entity).axes;
          constexpr auto groundFriction = glm::vec3(6.0f);
          friction                      = groundFriction;
          if (cs->character->GetGroundState() == JPH::CharacterBase::EGroundState::OnGround)
          {
            deltaVelocity += input.jump ? gUp * 8.0f : glm::vec3(0);
            // Make it possible to launch entities up with an impulse
            if (cs->previousGroundState == JPH::CharacterBase::EGroundState::OnGround)
            {
              velocity.y = 0;
            }
          }
          else
          {
            constexpr float airControl = 0.4f;
            constexpr auto airFriction = glm::vec3(0.05f);
            friction                   = airFriction;
            deltaVelocity.x *= airControl;
            deltaVelocity.z *= airControl;
            // const auto prevY = cs->character->GetLinearVelocity().GetY();
            // deltaVelocity += glm::vec3{0, prevY - 15 * dt, 0};
            deltaVelocity += glm::vec3{0, -15 * dt, 0};
          }
          friction.y = 0;

          // Apply friction
          auto newVelocity = glm::vec3(velocity.x, 0, velocity.z);
          // newVelocity -= friction * newVelocity * dt;

          // Apply dv
          newVelocity.x += deltaVelocity.x;
          newVelocity.z += deltaVelocity.z;

          // Clamp xz speed
          const float speed = glm::length(newVelocity);
          if (speed > attribs->runMaxSpeed)
          {
            newVelocity = glm::normalize(newVelocity) * attribs->runMaxSpeed;
          }

          // Y is not affected by speed clamp or friction
          newVelocity.y = velocity.y + deltaVelocity.y;

          registry_.get<LinearVelocity>(entity).v = newVelocity;
        }
      }
    }
  }
}
